### ISSUE TITLE
Using Elephant Shed with custom data directories

### ISSUE THREAD

**Issue by jakobhaeu** [credativ/elephant-shed#15]
Hi,

I am currently trying to use the current stable release of Elephant Shed with custom PostgreSQL data directories. My data directories are named like /pgdata/pg1_1000 (1 & 1000 are variable) but the bin-directories are the default ones. 
I already tried the solution from issue #7 .  
I ran:
ln -s /pgdata/pg1_1000 /var/lib/postgresql/12/pg1_1000
ln -s /pgdata/pg1_1000 /etc/postgresql/12/pg1_1000

Then I also tried linking our custom service unit for systemd:
ln -s /etc/systemd/system/pg1_1000.service /lib/systemd/system/postgresql@12-pg1_1000.service

The cluster is correctly shown typing pg_lsclusters.
Then I implemented the recommended postgresql.conf for elephant-shed, but it still does not show up in the Elephant-Shed GUI.
But I recognized that pgBadger was showing a report for the cluster I created. So the link looks to be  working.

What am I supposed to do to get my custom Postgres data directories to work with Elephant Shed?
Am I missing someting?

Thank you for your help.

**Comment by df7cb** [comment]
Hi Jakob,

if the clusters are seen by `pg_lsclusters` but not the webinterface, the problem is probably with read permissions on the postgresql.conf file: both the file and the /etc/postgresql/* directories need to be world-readable.

The same problem should be seen if you invoke pg_lsclusters as any user other than root or postgres (or more specifically, the cluster owner).

Does that fix the problem for you?

Christoph

**Comment by jakobhaeu** [comment]
Yes that fixed it.
Running pg_lsclusters as non-root user did not show the custom cluster.
I changed the permissions of all the folders and files of Postgres to 755 and now it is shown with pg_lsclusters and in the webinterface.

Thank you

Jakob

**Comment by df7cb** [comment]
Glad to hear that. Thanks for the feedback!
