### ISSUE TITLE
ferm not installed on Debian 10

### ISSUE THREAD

**Issue by debalance** [credativ/elephant-shed#16]
Hi,
I did the package based installation on Debian 10.
Contrary to the docs, there is no trace of ferm to be found.

**Comment by df7cb** [comment]
Hi,
long time no see :)
We'll look into fixing this, thanks for spotting!
Christoph

**Comment by df7cb** [comment]
The current situation is that the ferm rules are only installed via the ansible/vagrant setup. The deb/rpm packages currently do not install them because it is unclear if it's ok (or expected) to activate some firewall system on a machine that might already be set up otherwise.

We'll keep the issue open while we ponder about that - one possible resolution might be to just drop that note from the docs.

**Comment by debalance** [comment]
Those are valid concerns that I more or less expected, as I had already discovered the ansible tasks regarding ferm.
I would suggest to put those concerns in the docs and add an optional meta package for the ferm rules that must be manually installed.
