### ISSUE TITLE
Support for Ubuntu Server

### ISSUE THREAD

**Issue by Int32Overflow** [credativ/elephant-shed#2]
Hey,

this product looks really good. Do you also plan to support Ubuntu Server?

**Comment by disco-stu** [comment]
Hi,

Currently we only support Debian stretch (amd64 and ppc64el). But, the effort that's required to run the stack on Ubuntu server should be relative small. I guess you're looking for Ubuntu 16.04 LTS server packages?
Long-term we plan to provide packages for the latest versions of Debian, Ubuntu, RHEL and CentOS.

**Comment by Int32Overflow** [comment]
Yes your right, I'm looking for Ubuntu Server 16.04 LTS support.

**Comment by disco-stu** [comment]
I'm not sure if 16.04 LTS works out of the box, yet. However, you give it a try and report your results. I will also try to setup a test machine, but that might take a while.

**Comment by Int32Overflow** [comment]
No, unfortunately it does not work under Ubuntu 16.04.

What I have done:

`
sudo apt-get install curl ca-certificates apt-transport-https`

**=> nothing todo (allready installed)**


```
echo "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" | sudo tee -a /etc/apt/sources.list.d/pgdg.list
curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
```
**=> Correct repository for Ubuntu**

```
echo "deb https://packages.credativ.com/public/postgresql/ stretch-stable main" | sudo tee -a /etc/apt/sources.list.d/elephant-shed.list
curl https://packages.credativ.com/public/postgresql/aptly.key | sudo apt-key add -
```

```
add-apt-repository ppa:cockpit-project/cockpit
```
**=> Cockpit ppa for the required version (missing dependencies)**

Still missing dependencies:
- elephant-shed-pgadmin4
   - python3-flask-login 

I downloaded "python3-flask-login" and installed it as binary:

```
wget http://ftp.br.debian.org/debian/pool/main/f/flask-login/python3-flask-login_0.4.0-1_all.deb
dpkg -i python3-flask-login_0.4.0-1_all.deb
apt-get install -f
```

And then:

```
apt-get update
apt-get install elephant-shed
```


But installation process aborts with an error!

```
notification-daemon (3.18.2-1) wird eingerichtet ...
Trigger für libc-bin (2.23-0ubuntu9) werden verarbeitet ...
Trigger für systemd (229-4ubuntu21) werden verarbeitet ...
Trigger für ureadahead (0.100.0-19) werden verarbeitet ...
Trigger für ufw (0.35-0ubuntu2) werden verarbeitet ...
Trigger für libgdk-pixbuf2.0-0:amd64 (2.32.2-1ubuntu1.3) werden verarbeitet ...
Trigger für dbus (1.10.6-1ubuntu3.3) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 elephant-shed-prometheus
 elephant-shed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by disco-stu** [comment]
Root cause for the problem you run into is the elephant-shed-prometheus postinst script. It calls deb-systemd-helper to enable prometheus.service as well as the prometheus-node-exporter.service. This runs fine in Debian stretch. However, for some reason it fails on Ubuntu 16.04. If one comment out the two lines the installation succeeds.

More bad news: the next error you will run into is the outdated version of prometheus that is shipped with Ubuntu 16.04 (0.16.2+ds-1ubuntu1). That makes the monitoring stack unusable.

As far as I can tell we need the following fixes:
  - Ship missing dependencies in 16.04 for pgAdmin4 and Cockpit
  - Fix the postinst script
  - Ship a up to date version of prometheus

**Comment by Int32Overflow** [comment]
Thanks for your reply.

> Ship missing dependencies in 16.04 for pgAdmin4 and Cockpit

this will not be the problem. For pgAdmin4 the dependencies are in the official postgresql repository and for cockpit a ppa exists.

> Fix the postinst script

can you fix this?

> Ship a up to date version of prometheus

Which version is needed?

Or should we focus on Ubuntu 18.04 instead of Ubuntu 16.04? This new version should not have the dependency problems ...

**Comment by disco-stu** [comment]
Our intend is to keep the list of third party repositories as small as possible. We plan to get pgAdmin4 and friends into apt.postgresql.org but unfortunately that's not happen, yet.

Waiting for Ubuntu 18.04 is definitely an option. I personally prefer this option.
For now we use the prometheus version that's shipped with Debian (1.5.2+ds-2+b3).

I will have a look at the postinst script.

**Comment by ChristophBerg** [comment]
As an intermediate data point, installing Elephant Shed on Ubuntu Bionic 18.04 Just Works using the stretch repository. We'll polish that up and properly announce it shortly.

**Comment by disco-stu** [comment]
Hi @Int32Overflow 

Elephant Shed Ubuntu Bionic support isn't official released, yet. However, all packages are already present within the new "bionic-test" distribution on https://packages.credativ.com/public/postgresql. Feel free to give it a try. Feedback is very welcome.

To install Elephant Shed on Ubuntu 18.04 please follow the official installation guide but use bionic-test instead of stretch-stable or stretch-test.

**Comment by ChristophBerg** [comment]
bionic is officially supported now, see https://elephant-shed.io/project/ubuntu/
